### ISSUE TITLE
display list wrong

### ISSUE THREAD

**Issue by spayton** [Ariorh1337/phaser-debug-tool#2]
In the current version upto this commit [606eda5ea8e9e7ff1f9c5c3f180817b5f96ce807](https://github.com/Ariorh1337/phaser-debug-tool/commit/606eda5ea8e9e7ff1f9c5c3f180817b5f96ce807)

The scene display list isn't right.  The debug panel shows 6 children, but only the top two containers are present (as seen in the console log of the scene's display list.

![image](https://user-images.githubusercontent.com/4949575/229776808-b0808d90-cbb4-479f-ad0e-2036405420d5.png)

could these be destroyed objects?

**Comment by Ariorh1337** [comment]
there is a possibility that there is a problem with the missing "add" and "addAt" handlers, please check issue on version 0.1.7

**Comment by Ariorh1337** [comment]
reproduced the problem, it seems to be a problem with the cascading destruction of folders in tweakpane

<img width="1431" alt="NVIDIA_Share_kPlGDVdJmD" src="https://user-images.githubusercontent.com/35579597/230796135-8223b762-7ae1-4f59-a884-8b918f390f13.png">

**Comment by spayton** [comment]
using the latest version, if I null all the 'scene' propeties of the destroyed objects then they now do disappear from the children list
