### ISSUE TITLE
container addAt doesn't seem to be working

### ISSUE THREAD

**Issue by spayton** [Ariorh1337/phaser-debug-tool#3]
If I have a container with some exising children, then add something twith addAt(obj,0), it doesn't get placed at the beginning.

If I disable the extension it works as expected, ie the obj get added to start of container child list.

**Comment by spayton** [comment]
That has fixed the problem I observed, thanks

**Comment by spayton** [comment]
I spoke too soon.  At a glance the display order was now correct and the client was running as expected, but checking the debug entries showed them being out of sync.

The 'grpGameRoot' container holds 3 items, the order shown in the console pane is correct and the 'bg' element was added with addAt(bg,0).

The order shown in the debug children list is incorrect and clicking on the the middle item 'image' throws the exception.

**Comment by Ariorh1337** [comment]
`clicking on the the middle item 'image' throws the exception.`

please attach an example code or a screenshot of the error, the expected behavior is the order of the elements in the debug panel is not correct, but all the elements are working fine

**Comment by spayton** [comment]
Sorry, forgot to attach screenshot.  Here it is again on the updated v0.1.8

![image](https://user-images.githubusercontent.com/4949575/231103281-8d74b0d9-5032-40a6-89e5-cb51a8e2bacc.png)

**Comment by Ariorh1337** [comment]
try latest commit https://github.com/Ariorh1337/phaser-debug-tool/commit/6ed9dd304762130f32ac174ebc6aa40fd0c1a187

**Comment by spayton** [comment]
Yup, that no longer throws.  I also noticed that it no longer displays the name property next to the game object type, which was super useful, even though you had to click it to update the name display, would have been even better if they were all pre-populated.

**Comment by spayton** [comment]
Thats now got the name property being displayed... and without needing a click, great.
