### ISSUE TITLE
Visibility 'eye' button

### ISSUE THREAD

**Issue by spayton** [Ariorh1337/phaser-debug-tool#4]
Just a suggestion, but I think the display of this button state is reversed and is the opposite of what most people would expect.

Currently, the closed 'eye' will set a game object invisible if clicked.  Its icon shows what will happen if you click it, the state you will change too.

The opposite is probably more common, where what you see on the button is the current state.  So here, the open eye would mean the item is currently visible.

**Comment by Ariorh1337** [comment]
agree, the icon should display the current state of the game object instead of the intended behavior
